import os
import psycopg
from pathlib import Path
from dotenv import load_dotenv
# Load environment variables
load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://localhost/chatbot")

class PostgresRow:
    """
    A custom row object mimicking sqlite3.Row.
    Supports both positional indexing (row[0]) and key lookup (row['col']).
    Also supports unpacking (role, content = row).
    """
    def __init__(self, data, description):
        self._data = data  # tuple of values
        self._keys = [desc.name for desc in description] if description else []
        self._key_map = {name: i for i, name in enumerate(self._keys)}

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._data[key]
        elif isinstance(key, str):
            idx = self._key_map.get(key)
            if idx is None:
                raise KeyError(key)
            return self._data[idx]
        else:
            raise TypeError("Row indices must be integers or strings")

    def __len__(self):
        return len(self._data)

    def __iter__(self):
        return iter(self._data)

    def keys(self):
        return self._keys

    def values(self):
        return self._data

    def items(self):
        return [(k, self._data[i]) for k, i in self._key_map.items()]

    def __repr__(self):
        return f"PostgresRow({dict(self.items())})"


def postgres_row_factory(cursor):
    """
    Psycopg 3 row factory returning PostgresRow.
    """
    description = cursor.description
    def make_row(values):
        return PostgresRow(values, description)
    return make_row


class DatabaseManager:
    """
    Handles all PostgreSQL database operations.
    """

    def __init__(self, database_name=DATABASE_URL):

        self.database_name = database_name

        self.initialize_database()

    def get_connection(self):
        """
        Create a PostgreSQL connection with custom row factory.
        """
        conn = psycopg.connect(self.database_name, row_factory=postgres_row_factory)
        return conn

    def initialize_database(self):
        """
        Create required tables if they do not exist.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS users(
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        email TEXT UNIQUE NOT NULL,
                        password_hash TEXT NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)

                cursor.execute("""
                CREATE TABLE IF NOT EXISTS conversations (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    title TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(user_id)
                    REFERENCES users(id) ON DELETE CASCADE
                )
                """)

                cursor.execute("""
                CREATE TABLE IF NOT EXISTS messages (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    conversation_id INTEGER NOT NULL,
                    role TEXT,
                    content TEXT,
                    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(conversation_id)
                    REFERENCES conversations(id) ON DELETE CASCADE
                )
                """)

                # Migration: Check if user_id column exists in conversations table
                # rewritten using information_schema.columns to preserve the same migration behavior.
                cursor.execute("""
                    SELECT column_name AS name
                    FROM information_schema.columns
                    WHERE table_name = 'conversations'
                """)
                columns = [row["name"] for row in cursor.fetchall()]
                if "user_id" not in columns:
                    cursor.execute("ALTER TABLE conversations ADD COLUMN user_id INTEGER NOT NULL DEFAULT 1")

                cursor.execute("""
                CREATE TABLE IF NOT EXISTS documents (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL,
                    conversation_id INTEGER NOT NULL,
                    original_filename TEXT NOT NULL,
                    stored_filename TEXT NOT NULL,
                    file_path TEXT NOT NULL,
                    vectorstore_path TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
                    FOREIGN KEY(conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
                )
                """)

                # Create indexes where appropriate for foreign keys
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id)")
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id)")
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_documents_user_id ON documents(user_id)")
                cursor.execute("CREATE INDEX IF NOT EXISTS idx_documents_conversation_id ON documents(conversation_id)")

    def create_user(self, name, email, password_hash):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO users(name, email, password_hash)
                    VALUES (%s, %s, %s)
                    """,
                    (name, email, password_hash)
                )

    def get_user_by_email(self, email):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT * FROM users
                    WHERE email = %s
                    """,
                    (email,)
                )
                return cursor.fetchone()

    def get_user(self, user_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT *
                    FROM users
                    WHERE id = %s
                    """,
                    (user_id,)
                )
                return cursor.fetchone()

    def show_tables(self):
        """
        Display all database tables.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT table_name AS name
                    FROM information_schema.tables
                    WHERE table_schema='public'
                """)
                return cursor.fetchall()

    def create_conversation(self, title="New Chat", user_id=None):
        """
        Create a new conversation.

        Parameters
        ----------
        title : str
            Conversation title.
        user_id : int, optional
            The user ID this conversation belongs to.

        Returns
        -------
        int
            Newly created conversation ID.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                # If user_id is not provided, try to find a default user or use a dummy ID like 1 if no user exists.
                if user_id is None:
                    try:
                        import streamlit as st
                        if "user_id" in st.session_state and st.session_state.user_id is not None:
                            user_id = st.session_state.user_id
                    except ImportError:
                        pass

                if user_id is None:
                    cursor.execute("SELECT id FROM users LIMIT 1")
                    row = cursor.fetchone()
                    if row:
                        user_id = row[0]
                    else:
                        user_id = 1 # Fallback dummy ID

                cursor.execute(
                    """
                    INSERT INTO conversations (user_id, title)
                    VALUES (%s, %s)
                    RETURNING id
                    """,
                    (user_id, title)
                )
                row = cursor.fetchone()
                conversation_id = row[0]
                return conversation_id

    def get_all_conversations(self, user_id=None):
        """
        Return all conversations.

        Parameters
        ----------
        user_id : int, optional
            Filter conversations by this user ID.

        Returns
        -------
        list
        """

        if user_id is None:
            try:
                import streamlit as st
                if "user_id" in st.session_state and st.session_state.user_id is not None:
                    user_id = st.session_state.user_id
            except ImportError:
                pass

    def get_all_conversations(self, user_id=None):
        """
        Return all conversations.

        Parameters
        ----------
        user_id : int, optional
            Filter conversations by this user ID.

        Returns
        -------
        list
        """
        if user_id is None:
            try:
                import streamlit as st
                if "user_id" in st.session_state and st.session_state.user_id is not None:
                    user_id = st.session_state.user_id
            except ImportError:
                pass

        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                if user_id is not None:
                    cursor.execute("""
                        SELECT
                            id,
                            title,
                            created_at
                        FROM conversations
                        WHERE user_id = %s
                        ORDER BY created_at DESC
                    """, (user_id,))
                else:
                    cursor.execute("""
                        SELECT
                            id,
                            title,
                            created_at
                        FROM conversations
                        ORDER BY created_at DESC
                    """)
                return cursor.fetchall()

    def get_conversation(self, conversation_id):
        """
        Return one conversation.

        Parameters
        ----------
        conversation_id : int

        Returns
        -------
        tuple | None
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT
                        id,
                        title,
                        created_at
                    FROM conversations
                    WHERE id = %s
                    """,
                    (conversation_id,)
                )
                return cursor.fetchone()

    def update_conversation_title(
        self,
        conversation_id,
        new_title
    ):
        """
        Update conversation title.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE conversations
                    SET title = %s
                    WHERE id = %s
                    """,
                    (new_title, conversation_id)
                )

    def delete_conversation(self, conversation_id):
        """
        Delete a conversation and all related messages.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM messages
                    WHERE conversation_id = %s
                    """,
                    (conversation_id,)
                )
                cursor.execute(
                    """
                    DELETE FROM documents
                    WHERE conversation_id = %s
                    """,
                    (conversation_id,)
                )
                cursor.execute(
                    """
                    DELETE FROM conversations
                    WHERE id = %s    
                    """,
                    (conversation_id,)
                )

    def save_message(
        self,
        conversation_id,
        role,
        content
    ):
        """
        Save a single message to the database.

        Parameters
        ----------
        conversation_id : int
        role : str
            "user" or "assistant"
        content : str
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO messages (
                        conversation_id,
                        role,
                        content
                    )
                    VALUES (%s, %s, %s)
                    """,
                    (
                        conversation_id,
                        role,
                        content
                    )
                )

    def get_messages(self, conversation_id):
        """
        Retrieve all messages for a conversation.

        Parameters
        ----------
        conversation_id : int

        Returns
        -------
        list
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT
                        role,
                        content,
                        timestamp
                    FROM messages
                    WHERE conversation_id = %s
                    ORDER BY id ASC
                    """,
                    (conversation_id,)
                )
                return cursor.fetchall()

    def delete_messages(self, conversation_id):
        """
        Delete all messages for a conversation.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM messages
                    WHERE conversation_id = %s
                    """,
                    (conversation_id,)
                )

    def clear_chat_history(self, conversation_id):
        """
        Alias for delete_messages.
        """
        return self.delete_messages(conversation_id)

    def load_chat_history(self, conversation_id):
        """
        Load conversation history in Streamlit format.

        Returns
        -------
        list
        """
        messages = self.get_messages(conversation_id)
        history = []
        for row in messages:
            role = row["role"]
            content = row["content"]
            history.append({
                "role": role,
                "content": content
            })
        return history

    def add_document(self, user_id, conversation_id, original_filename, stored_filename, file_path, vectorstore_path=None):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO documents (user_id, conversation_id, original_filename, stored_filename, file_path, vectorstore_path)
                    VALUES (%s, %s, %s, %s, %s, %s)
                    RETURNING id
                    """,
                    (user_id, conversation_id, original_filename, stored_filename, str(file_path), str(vectorstore_path) if vectorstore_path else None)
                )
                row = cursor.fetchone()
                doc_id = row[0]
                return doc_id

    def get_documents_by_conversation(self, conversation_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT * FROM documents
                    WHERE conversation_id = %s
                    ORDER BY created_at ASC
                    """,
                    (conversation_id,)
                )
                return [dict(row) for row in cursor.fetchall()]

    def get_documents_by_user(self, user_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT * FROM documents
                    WHERE user_id = %s
                    ORDER BY created_at ASC
                    """,
                    (user_id,)
                )
                return [dict(row) for row in cursor.fetchall()]

    def delete_document(self, document_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM documents
                    WHERE id = %s
                    """,
                    (document_id,)
                )

    def delete_conversation_documents(self, conversation_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM documents
                    WHERE conversation_id = %s
                    """,
                    (conversation_id,)
                )

    def update_vectorstore_path(self, conversation_id, vectorstore_path):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE documents
                    SET vectorstore_path = %s
                    WHERE conversation_id = %s
                    """,
                    (str(vectorstore_path) if vectorstore_path else None, conversation_id)
                )

    def get_vectorstore_path(self, conversation_id):
        with self.get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    SELECT vectorstore_path FROM documents
                    WHERE conversation_id = %s AND vectorstore_path IS NOT NULL
                    LIMIT 1
                    """,
                    (conversation_id,)
                )
                row = cursor.fetchone()
                return row[0] if row else None

    def reset_database(self):
        """
        Delete all tables and recreate them.
        """
        with self.get_connection() as connection:
            with connection.cursor() as cursor:
                cursor.execute("DROP TABLE IF EXISTS messages CASCADE")
                cursor.execute("DROP TABLE IF EXISTS documents CASCADE")
                cursor.execute("DROP TABLE IF EXISTS conversations CASCADE")
                cursor.execute("DROP TABLE IF EXISTS users CASCADE")
        self.initialize_database()
database = DatabaseManager()


def create_user(name, email, password_hash):
    return database.create_user(name, email, password_hash)


def get_user_by_email(email):
    return database.get_user_by_email(email)


def get_user(user_id):
    return database.get_user(user_id)


def add_document(user_id, conversation_id, original_filename, stored_filename, file_path, vectorstore_path=None):
    return database.add_document(user_id, conversation_id, original_filename, stored_filename, file_path, vectorstore_path)


def get_documents_by_conversation(conversation_id):
    return database.get_documents_by_conversation(conversation_id)


def get_documents_by_user(user_id):
    return database.get_documents_by_user(user_id)


def delete_document(document_id):
    return database.delete_document(document_id)


def delete_conversation_documents(conversation_id):
    return database.delete_conversation_documents(conversation_id)


def update_vectorstore_path(conversation_id, vectorstore_path):
    return database.update_vectorstore_path(conversation_id, vectorstore_path)


def get_vectorstore_path(conversation_id):
    return database.get_vectorstore_path(conversation_id)


def update_conversation_title(conversation_id, new_title):
    return database.update_conversation_title(conversation_id, new_title)


if __name__ == "__main__":
    print("Starting Database Verification Suite...")
    try:
        # 1. Reset Database
        print("Resetting database...")
        database.reset_database()
        
        # 2. Show Tables
        tables = database.show_tables()
        print("Database tables after initialization:")
        for t in tables:
            print(f" - {t[0]}")
        
        # 3. Create User
        print("Creating test user...")
        database.create_user(name="Test User", email="test@example.com", password_hash="dummyhash")
        
        # 4. Get User
        user = database.get_user_by_email("test@example.com")
        assert user is not None, "Failed to retrieve user by email"
        print(f"User retrieved by email: name={user['name']}, email={user['email']}")
        
        user_by_id = database.get_user(user['id'])
        assert user_by_id is not None, "Failed to retrieve user by id"
        print(f"User retrieved by ID: name={user_by_id['name']}")
        
        # 5. Create Conversation
        print("Creating conversations...")
        conv_id_1 = database.create_conversation(title="New Chat", user_id=user['id'])
        print(f"Created conversation 1, ID: {conv_id_1}")
        
        conv_id_2 = database.create_conversation(title="Another Chat", user_id=user['id'])
        print(f"Created conversation 2, ID: {conv_id_2}")
        
        # 6. Update Conversation Title
        database.update_conversation_title(conv_id_1, "Updated Chat Title")
        conv = database.get_conversation(conv_id_1)
        assert conv["title"] == "Updated Chat Title", f"Expected title 'Updated Chat Title', got {conv['title']}"
        print(f"Conversation title updated successfully: {conv['title']}")
        
        # 7. Save messages
        print("Saving chat messages...")
        database.save_message(conv_id_1, role="user", content="Hello, this is a test query.")
        database.save_message(conv_id_1, role="assistant", content="Hi! This is the assistant response.")
        
        # 8. Load messages
        msgs = database.get_messages(conv_id_1)
        print(f"Retrieved messages count: {len(msgs)}")
        for m in msgs:
            print(f"  [{m['role']}]: {m['content']}")
            
        history = database.load_chat_history(conv_id_1)
        print(f"Streamlit formatted history: {history}")
        
        # 9. Clear chat history
        print("Clearing chat history for conversation...")
        database.clear_chat_history(conv_id_1)
        msgs_after = database.get_messages(conv_id_1)
        assert len(msgs_after) == 0, "Messages were not cleared!"
        print("Message history successfully cleared.")
        
        # 10. Add document
        print("Adding document metadata...")
        doc_id = database.add_document(
            user_id=user['id'], 
            conversation_id=conv_id_2, 
            original_filename="sample.pdf", 
            stored_filename="stored_sample.pdf", 
            file_path="/path/to/stored_sample.pdf"
        )
        print(f"Document added with ID: {doc_id}")
        
        # 11. Update and get vectorstore path
        print("Updating vectorstore path...")
        database.update_vectorstore_path(conv_id_2, "/path/to/vectorstore")
        vs_path = database.get_vectorstore_path(conv_id_2)
        assert vs_path == "/path/to/vectorstore", f"Expected /path/to/vectorstore, got {vs_path}"
        print(f"Vectorstore path: {vs_path}")
        
        # 12. Get documents by user and conversation
        docs_conv = database.get_documents_by_conversation(conv_id_2)
        assert len(docs_conv) == 1, "Should have 1 document under conversation"
        print(f"Documents for conversation: {docs_conv[0]['original_filename']}")
        
        docs_user = database.get_documents_by_user(user['id'])
        assert len(docs_user) == 1, "Should have 1 document under user"
        print(f"Documents for user: {docs_user[0]['original_filename']}")
        
        # 13. Delete document
        print("Deleting document...")
        database.delete_document(doc_id)
        docs_conv_after = database.get_documents_by_conversation(conv_id_2)
        assert len(docs_conv_after) == 0, "Document was not deleted"
        print("Document deleted successfully.")
        
        # 14. Add document back for cascade delete testing
        doc_id_new = database.add_document(
            user_id=user['id'], 
            conversation_id=conv_id_2, 
            original_filename="sample_cascade.pdf", 
            stored_filename="stored_cascade.pdf", 
            file_path="/path/to/stored_cascade.pdf"
        )
        database.save_message(conv_id_2, role="user", content="Cascade test message.")
        
        # 15. Delete conversation (assert cascading delete)
        print("Deleting conversation 2 to test CASCADE deletion...")
        database.delete_conversation(conv_id_2)
        
        # Check messages for conv_id_2
        msgs_c2 = database.get_messages(conv_id_2)
        assert len(msgs_c2) == 0, "Cascade failed: messages for deleted conversation still exist."
        
        # Check documents for conv_id_2
        docs_c2 = database.get_documents_by_conversation(conv_id_2)
        assert len(docs_c2) == 0, "Cascade failed: documents for deleted conversation still exist."
        print("Cascade deletion verified: messages and documents were deleted automatically!")
        
        print("ALL TESTS PASSED SUCCESSFULLY! The PostgreSQL integration is complete and verified.")
    except Exception as err:
        import traceback
        print("Test suite failed with exception:")
        traceback.print_exc()
